name: thesis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - absl-py=2.1.0
  - alsa-lib=1.2.8
  - anndata=0.10.6
  - array-api-compat=1.5.1
  - asttokens=2.4.1
  - attr=2.5.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cycler=0.12.1
  - dbus=1.13.6
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.50.0
  - freetype=2.12.1
  - fsspec=2024.3.1
  - get-annotations=0.1.2
  - gettext=0.21.1
  - glib=2.80.0
  - glib-tools=2.80.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - graphite2=1.3.13
  - grpcio=1.59.3
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.38
  - h5py=3.9.0
  - harfbuzz=6.0.0
  - hdf5=1.14.1
  - icu=70.1
  - idna=3.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jack=1.9.22
  - jedi=0.19.1
  - joblib=1.3.2
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.0.20
  - libcups=2.3.3
  - libcurand=10.3.5.119
  - libcurl=8.1.2
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libgomp=13.2.0
  - libgpg-error=1.48
  - libgrpc=1.59.3
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.43
  - libpq=15.3
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=253
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxgboost=2.0.3
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lightning=2.2.1
  - lightning-utilities=0.11.0
  - llvm-openmp=15.0.7
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mkl=2022.2.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.4
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - natsort=8.4.0
  - nccl=2.21.5.1
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.2.1
  - nspr=4.35
  - nss=3.98
  - numba=0.59.0
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.5
  - packaging=24.0
  - pandas=2.2.1
  - parso=0.8.3
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=4.2.0
  - ply=3.11
  - prompt-toolkit=3.0.42
  - protobuf=4.24.4
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - py-xgboost=2.0.3
  - py-xgboost-gpu=2.0.3
  - pygments=2.17.2
  - pynndescent=0.5.11
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.2.1
  - pytorch-cuda=11.8
  - pytorch-lightning=2.2.1
  - pytorch-metric-learning=2.4.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - re2=2023.09.01
  - readline=8.2
  - requests=2.31.0
  - scanpy=1.9.8
  - scikit-learn=1.4.1.post1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - session-info=1.0.0
  - setuptools=69.2.0
  - sip=6.7.12
  - six=1.16.0
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - stdlib-list=0.10.0
  - sympy=1.12
  - tbb=2021.9.0
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - threadpoolctl=3.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=2.2.1
  - torchmetrics=1.3.2
  - torchtriton=2.2.0
  - torchvision=0.17.1
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.2
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - umap-learn=0.5.5
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - werkzeug=3.0.1
  - wheel=0.43.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - captum==0.7.0
      - cellrank==2.0.3
      - click==8.1.7
      - docrep==0.3.2
      - igraph==0.11.4
      - jinja2==3.0.3
      - loompy==3.0.7
      - numpy-groupies==0.10.2
      - progressbar2==4.4.2
      - pygam==0.9.1
      - pygpcca==1.0.4
      - pykan==0.0.2
      - python-utils==3.8.2
      - scipy==1.11.4
      - scvelo==0.3.2
      - texttable==1.7.0
      - torchensemble==0.1.9
      - upsetplot==0.9.0
      - wrapt==1.16.0
